[theme]
base = "dark"
primaryColor = "#22c55e"              # เขียว (match "Green")
backgroundColor = "#0b1220"           # ดำอมฟ้า
secondaryBackgroundColor = "#111827"  # พื้นการ์ด
textColor = "#e5e7eb"                 # เทาอ่อน
font = "sans serif"
